apiVersion: v1
kind: Service
metadata:
  name: test-app-svc
spec:
  type: NodePort
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30036
